# Generated by Django 2.2.5 on 2019-09-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
