# Generated by Django 2.2.6 on 2019-10-16 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(message='이메일 형식에 맞지 않습니다.')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(19, message='미성년자는 노노')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pk']},
        ),
    ]
