# Generated by Django 2.2.5 on 2019-09-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conten',
            new_name='content',
        ),
    ]
