# Generated by Django 2.2.6 on 2019-10-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Patient',
        ),
    ]
