# Generated by Django 2.2.6 on 2019-10-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0003_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', to='manytoone.Doctor'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
